title: <p align="center"> Shridevi Reddy </p>

logo: "/images/profile_pic.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/SHRIDEVI_REDDY.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shridevireddy/">LinkedIn</a> |
  <a href="https://github.com/ShrideviReddy">GitHub</a>
  </p>
  
  <p align="justify">
  I am Masters graduate with majors in Computer Science from University of North Carolina, Charlotte.
  <br><br>
  I am currently working as Machine Learning Research Intern at UNC, Charlotte with a focus on Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
