title: <p align="center"> Shridevi Reddy </p>

logo: "/images/profile_pic.jpg?raw=true"

description:
  <p align="center">
  <a href="images/SHRIDEVI_REDDY_RESUME.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shridevireddy/">LinkedIn</a> |
  <a href="https://github.com/ShrideviReddy">GitHub</a>
  </p>
  
  <p align="justify">
  I am Masters graduate with majors in Computer Science from University of North Carolina, Charlotte.
  <br><br>
  Currently working as Data Scientist at Bookscribs.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-179725566-1 # Google Analytics tracking ID
